dist: xenial
language: java
jdk: openjdk8
services: mysql
before_install:
  - mysql -e 'create database craftconomy;'
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report
