language: java
sudo: false
jdk:
  - oraclejdk8
services: mysql
before_install:
  #- 'if [[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == pavog/craftconomy3 ]] && [[ $TRAVIS_BRANCH == master ]]; then openssl aes-256-cbc -k "$opensslkey" -in key.gpg.enc -out key.gpg -d; fi'
  - mysql -e 'create database craftconomy;'
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report