version: '3'
services:

  # The Server
  minecraft:
    ports:
    - "25565:25565"
    volumes:
    - "mcdata:/data"
    - "./target:/plugins"
    environment:
      TYPE: SPIGOT
      VERSION: 1.13.2
      EULA: "TRUE"
      MAX_MEMORY: 4G
      MAX_PLAYERS: 100
      PVP: "true"
      OPS: "EvilCodes"
      CONSOLE: "false"
    image: itzg/minecraft-server
    restart: always
    networks:
    - app-net
    depends_on:
    - database

  # The RCON for the server
  rcon:
    image: itzg/rcon
    ports:
    - "4326:4326"
    - "4327:4327"
    volumes:
    - "rcon:/opt/rcon-web-admin/db"
    networks:
    - app-net
    depends_on:
    - database

  # MySQL
  database:
    image: mysql:5.7
    volumes:
    - dbdata:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_DATABASE=app
    - MYSQL_USER=app
    - MYSQL_PASSWORD=app_pw
    - MYSQL_ROOT_PASSWORD=secret_root_pw
    ports:
    - "3306:3306"
    hostname: database
    networks:
    - app-net

networks:
  app-net:

volumes:
  dbdata:
  mcdata:
  rcon: