name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - gh-actions

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: ''
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: 'Craftconomy'

    strategy:
      matrix:
        java-version: [ '8', '11', '17' ]
        spigot-version: [ '1_8', '1_9', '1_10', '1_11', '1_12', '1_13', '1_14', '1_15', '1_16' ]

    name: Run tests on Java v${{ matrix.java-version }} and Spigot v${{ matrix.spigot-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK v${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Run tests
        run: mvn test jacoco:report -P Spigot_${{ matrix.spigot-version }}
